name 'websites'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures websites'
long_description 'Installs/Configures websites'
version '0.1.0'
